# Generated by Django 3.0.8 on 2020-07-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentalMathWebsite', '0003_chatmessage_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
