# Generated by Django 3.0.8 on 2020-07-21 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MentalMathWebsite', '0005_auto_20200720_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('againstAI', models.BooleanField()),
                ('isCorrect', models.BooleanField()),
                ('typeOfProblem', models.CharField(max_length=1)),
                ('timeToFinish', models.FloatField()),
                ('dateOfProblem', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
